Fix patch command

diff --git a/k8s/chainctl b/k8s/chainctl
--- a/k8s/chainctl
+++ b/k8s/chainctl
@@ -20,8 +20,6 @@ if [ -z "$PROJECT_ID" ] || [ -z "$CLUSTER_NAME" ]; then
   exit 1
 fi
 
-ROLLOUT_PATCH='{"spec":{"template":{"spec":{"containers":[{"name":"CONTNAME","image":"CONTSHA"}]}}}}'
-
 # Use a local workspace kubeconfig rather than a global one
 export KUBECONFIG=$PWD/.kube/config
 
@@ -81,7 +79,7 @@ usage() {
   printf "\033[36m%-30s\033[0m %s\n" pull-secrets "Retrieve all secrets for this cluster as yaml files."
 
   printf "\033[36m%-30s\033[0m %s\n" apply "Apply the k8s configuration templates as specified by TEMPLATES."
-  printf "\033[36m%-30s\033[0m %s\n" patch "???"
+  printf "\033[36m%-30s\033[0m %s\n" patch "Pull the latest image for a <deployment>."
 
   printf "\033[36m%-30s\033[0m %s\n" info "Print useful k8s information such as pods, services and meta information."
   printf "\033[36m%-30s\033[0m %s\n" bootstrap-cluster "Create the whole cluster from scratch."
@@ -257,12 +255,19 @@ case "$1" in
     ;;
 
   patch)
+    if [ -z "$2" ] ; then
+      printf "Error: no deployment parameter supplied.\n\n"
+      usage
+      exit 1
+    fi
+    deployment="$2"
+
     select_gcloud_config
     select-cluster
     banner
-    # TODO: how to make this customizable for a deployment? make this just a sub-script?
-    kubectl patch deployment chainlink-deploy -p \
-      $(subst CONTSHA,$(shell ../docker-repodigest $(CHAINLINK_IMAGE)),$(subst CONTNAME,chainlink,$(ROLLOUT_PATCH)))
+
+    printf '{"spec":{"template":{"metadata":{"labels":{"date":"%s"}}}}}' `date +%s` \
+       | xargs -0 kubectl patch deployment $deployment -p
     ;;
 
   info)
